language: php
os:
- linux
before_deploy:
  - zip -r latest *
  - test -d dpl_cd_upload || mkdir dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
  - provider: s3
    access_key_id: $aws_access_key
    secret_access_key:
      secure: $aws_secure_key
    local_dir: dpl_cd_upload
    skip_cleanup: true
    region: us-esat-2
    on:
      branch: master
    bucket: "yn-test-codedeploy"
  - provider: codedeploy
    access_key_id: $aws_access_key
    secret_access_key:
      secure: $aws_secure_key
    bucket: "yn-test-codedeploy"
    key: latest.zip
    application: y-codedepoly-app
    deployment_group: master
    region: us-east-2
    on:
      branch: master
